### ISSUE TITLE
Can I use it in dotnet core 3.1?

### ISSUE THREAD

**Issue by TTonlyV5** [LiveOrDevTrying/Tcp.NET#2]
Can I use it in dotnet core 3.1?
It doesn't seem to work.

**Comment by LiveOrDevTrying** [comment]
Let me push a new build that either is uplifted to .net standard (will work in 3.1) or 3.1 compatible. I will post when its up.

Thanks,
Rob

**Comment by LiveOrDevTrying** [comment]
Hi @TTonlyV5,
v1.6.0 is now live (on github and nuget) and is built in .net standard. It will work with 3.1 now. Please let me know how it goes. Thanks!
Rob
