### ISSUE TITLE
Nuget Tcp.NET (6.0.40) - can't receive last packet

### ISSUE THREAD

**Issue by ghost** [LiveOrDevTrying/Tcp.NET#3]
[UnitTest1.txt](https://github.com/LiveOrDevTrying/Tcp.NET/files/9076113/UnitTest1.txt)

When I send one packet I receive one packet - so far so good.
However when I send two packets I receive only one packet, when I send three packets I receive only two packets etc.
I tried to listen for error events but there weren't any.

**Comment by LiveOrDevTrying** [comment]
Hello! Thank you for your comment and for posting the test. The code for Tcp.NET has been updated, and now this test succeed. Please give it a try. Thank you for using Tcp.NET and please reach out if you run into any other problems or have any concerns or suggestions. Thanks!
