### ISSUE TITLE
Can't initialize ParamsTcpServer and ParamsTcpClient when endOfLineBytes is provided

### ISSUE THREAD

**Issue by ghost** [LiveOrDevTrying/Tcp.NET#4]
Nuget Tcp.Net (6.0.40) 

 _var port = 8989;
 var bytes = new byte[] { 13, 10 };
 new ParamsTcpServer(port, bytes);
 new ParamsTcpClient("localhost", port, bytes, isSSL: false);_

It causes NullReferenceException because of missing _pingBytes_ and _pongBytes_ null validations

**Comment by LiveOrDevTrying** [comment]
Great catch! I just pushed a fix. Ty!
