### ISSUE TITLE
Can Ping be an optional feature?

### ISSUE THREAD

**Issue by gkapellmann** [LiveOrDevTrying/Tcp.NET#5]
I really like the Ping / Pong feature, it makes a lot of sense, but I want to be able to ue this class with other devices that use TCP communication as well. 

If I was only designing my own comms, then no prob. But I will also interact with other devices that are already developed.

Could we do this optional?

Thank you

**Comment by gkapellmann** [comment]
Just as I created this issue, I just put a 0 in the pingIntervalSec. Seems to be working, as I dont get a Ping request now. Is this how it is meant to be used?

I didn't find anything in the doc's mentioning this.

**Comment by LiveOrDevTrying** [comment]
This is a great idea. I will make this change and post an update and then confirm here.

Thanks,

**Comment by LiveOrDevTrying** [comment]
This change has been pushed and new packages are available. Ty for using Tcp.NET! :D
