### ISSUE TITLE
Parameter input error

### ISSUE THREAD

**Issue by 604980670** [LiveOrDevTrying/Tcp.NET#8]
version 7.0.23
var eol = System.Encoding.UTF8.GetBytes("\r\n");
    ITcpNETClient client = new TcpNETClient(new ParamsTcpClientBytes("connect.tcp.net", 8989, eol, isSSL: false);

ParamsTcpClientBytes Parameters will report errors

**Comment by LiveOrDevTrying** [comment]
Will review this today

**Comment by LiveOrDevTrying** [comment]
@604980670 Great catch! Pushed a new version which is live now:

Use this constructor:

var eol = System.Encoding.UTF8.GetBytes("\r\n");
ITcpNETClient client = new TcpNETClient(new ParamsTcpClientBytes("connect.tcp.net", 8989, eol, isSSL: false));

Make sure to set the variable onlyEmitBytes = true for client and server if you dont want messages to decode into string.

I need to still update the documentation. Please let me know if this works and if you confirm it does, I will close this issue.

Ty for using Tcp.NET!

**Comment by 604980670** [comment]
After the ParamsTcpClientBytes parameter is passed in, Visual Studio ID prompts that it cannot be converted from "Tcp. NET. Client. Models. ParamsTcpClientBytes" to "Tcp. NET. Client. Models. ParamsTcpClient"

**Comment by LiveOrDevTrying** [comment]
Reviewing, just another moment

**Comment by LiveOrDevTrying** [comment]
Nuget does a bad job with including updated dependent packages. New package building now - should be updated shortly. Will post when ready.

**Comment by 604980670** [comment]
Thank you

**Comment by LiveOrDevTrying** [comment]
Bug is on my CICD pipeline.  30 min more and will have a package for you.

**Comment by LiveOrDevTrying** [comment]
@604980670 

Try deleting your bin and obj directories, update packages, clean, and rebuild. Should be working now.  I'll fix my CICD pipeline - NuGet is fine.

Let met know how it goes!

**Comment by LiveOrDevTrying** [comment]
@604980670 .

Has this been resolved? If yes, I can close this issue.

Thanks,
Rob
