### ISSUE TITLE
API interface required

### ISSUE THREAD

**Issue by 604980670** [LiveOrDevTrying/Tcp.NET#9]
Is there an API interface for the client to wait for the verification to be completed to send the message, I want to send it as soon as the connection is completed.

**Comment by LiveOrDevTrying** [comment]
Should be handled by the package. Make sure to await ConnectAsync() - If there is an auth token, it will be delivered as first message and digested, and / or if no auth token is passed, then method should wait for ConnectionEvent Connected, then complete async method. Then when you await SendMessage(), your messages will be delivered. If this doesn't work right, I can add a queue, but this would not be ideal - messages sent in a disconnected state (e.g. connection method / send message running in parallel) should be discarded I believe. Let me confirm.

**Comment by LiveOrDevTrying** [comment]
Negative - no messages will be sent until this event is fired. I will add in a queue and TTL to address this. Standby for update - will take ~24 hours

**Comment by LiveOrDevTrying** [comment]
You should be able to await ConnectAsync() and when completed, messages sent with await SendAsync() should be sent. No queue required for this. Please confirm - if I am wrong I will post a fix.

**Comment by 604980670** [comment]
Send immediately after connection, and a verification failure will be reported. You must wait until the verification is successful before sending,

**Comment by 604980670** [comment]
I want to have a waiting interface to avoid sending failures

**Comment by LiveOrDevTrying** [comment]
Yes exactly - try await ConnectAsync(). I believe this is what you want.  Let me know how it goes.

**Comment by 604980670** [comment]
thanks

**Comment by LiveOrDevTrying** [comment]
Check out the latest package and let me know how it goes plz.

**Comment by LiveOrDevTrying** [comment]
@604980670 .

Has this been resolved? If yes, I can close this issue.

Thanks,
Rob
